# Config file for automatic testing at travis-ci.org

language: python
sudo: false
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

before_install:
  - pip install -U pip

install:
  - pip install -U .[reco]
  - pip install strict-rfc3339 jsonschema
  - python setup.py test

script: py.test
